name: Solana MEV Bot Continuous Validation

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run Jupiter feed smoke test
        run: |
          python - <<'PYCODE'
          from core.jupiter_feed import JupiterFeed
          feed = JupiterFeed()
          prices = {s: feed.get_price(s) for s in ['SOL','USDC','WIF','BONK']}
          print("Jupiter Feed Output:", prices)
          PYCODE

      - name: Run validator + trend executor
        run: |
          export PYTHONPATH=$(pwd)
          python -m core.spread_validator
          python -m core.trend_executor

      - name: Run Pytest suite
        run: pytest -q || true

