name: "Stage25 — Working Price Feed with Auto-Testing"

on:
  workflow_run:
    workflows: ["Stage24 — Reset & Data Fix"]
    types: [completed]
  workflow_dispatch:

jobs:
  pricefeed_autotest:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pytest

      - name: Run Price Feed Auto-Test
        run: |
          python - <<'EOF'
          import requests, pandas as pd, json, time

          # Fetch Raydium and Orca prices
          urls = {
              "raydium": "https://api.raydium.io/v2/main/price",
              "orca": "https://api.mainnet.orca.so/allPools"
          }

          data = {}
          for name, url in urls.items():
              try:
                  r = requests.get(url, timeout=10)
                  data[name] = {"status": r.status_code, "length": len(r.text)}
              except Exception as e:
                  data[name] = {"error": str(e)}

          # Save and print summary
          df = pd.DataFrame(data).T
          df.to_csv("data/pricefeed_test_output.csv")
          print("\n=== Summary ===")
          print(df)
          EOF

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stage25-pricefeed-results
          path: data/pricefeed_test_output.csv

